<?php

namespace PrManagerBundle\Repository;

/**
 * eb_projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eb_projetRepository extends \Doctrine\ORM\EntityRepository
{
}
