<?php

namespace PrManagerBundle\Repository;

/**
 * eb_roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eb_roleRepository extends \Doctrine\ORM\EntityRepository
{
}
