<?php

namespace PrManagerBundle\Repository;

/**
 * eb_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eb_utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
